//
//  AlbumInteractor.swift
//  PulentChallenge2
//
//  Created by Felipe Loyola on 28-07-20.
//  Copyright (c) 2020 Felipe Loyola. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AlbumInteractor {
    var songService: ISongService!
    var output: AlbumInteractorOutput!
}

// MARK: - Extensions -

extension AlbumInteractor: AlbumInteractorInterface {
    func getSongs(albumId: Int) {
        self.songService.getAlbumSongs(albumId: albumId, success: { songs in
            self.output.presentSongs(songs: songs.map(self.parseSongs))
        }, error: {
            self.output.presentErrorOnServer()
        })
    }
    private func parseSongs(song: SongModel) -> AlbumSongViewModel {
        .init(position: song.trackNumber, name: song.trackName)
    }
}
