//
//  AlbumInterfaces.swift
//  PulentChallenge2
//
//  Created by Felipe Loyola on 28-07-20.
//  Copyright (c) 2020 Felipe Loyola. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AlbumWireframeInterface: WireframeInterface {
}

protocol AlbumViewInterface: ViewInterface {
}

protocol AlbumPresenterInterface: PresenterInterface {
}

protocol AlbumInteractorInterface: InteractorInterface {
}
