//
//  AlbumWireframe.swift
//  PulentChallenge2
//
//  Created by Felipe Loyola on 28-07-20.
//  Copyright (c) 2020 Felipe Loyola. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AlbumWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = AlbumViewController()
        super.init(viewController: moduleViewController)

        let interactor = AlbumInteractor()
        let presenter = AlbumPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension AlbumWireframe: AlbumWireframeInterface {
}
