//
//  AlbumViewController.swift
//  PulentChallenge2
//
//  Created by Felipe Loyola on 28-07-20.
//  Copyright (c) 2020 Felipe Loyola. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AlbumViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: AlbumPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension AlbumViewController: AlbumViewInterface {
}
