//
//  AlbumInteractor.swift
//  PulentChallenge2
//
//  Created by Felipe Loyola on 28-07-20.
//  Copyright (c) 2020 Felipe Loyola. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AlbumInteractor {
}

// MARK: - Extensions -

extension AlbumInteractor: AlbumInteractorInterface {
}
